<template>
    <div class="p-6">
        <div class="flex flex-wrap justify-center">
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
            <div class="p-2">
                <div
                    class="
                        rounded-full
                        h-24
                        w-24
                        flex
                        items-center
                        justify-center
                        bg-green-600
                        m-auto
                    "
                >
                    Circle
                </div>
                <div>
                    Encrypt_Decrypt
                </div>
            </div>
        </div>
    </div>
</template>
